version: '3'

services:
     mysql:
         build: .
         container_name: mysql
         networks:
             - dev-network
         ports: 
             - "3306:3306"
         environment:
             MYSQL_ROOT_PASSWORD: mysql

networks:
    dev-network:
    
volumes:
    app:
        driver: 'local'
