version: '3'

services:
     mysql:
         build: .
         container_name: mysql
         command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
         networks:
             - dev-network
         ports: 
             - "3306:3306"
         environment:
             MYSQL_ROOT_PASSWORD: mysql
             MYSQL_USER: user
             MYSQL_PASSWORD: user


networks:
    dev-network:
    
volumes:
    app:
        driver: 'local'
